package io.github.riemr.shift.infrastructure.persistence.entity;

import java.io.Serializable;

public class ConstraintMaster implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_master.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String constraintCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_master.description
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_master.default_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String defaultKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_master.default_weight
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer defaultWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_master.constraint_code
     *
     * @return the value of public.constraint_master.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getConstraintCode() {
        return constraintCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_master.constraint_code
     *
     * @param constraintCode the value for public.constraint_master.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setConstraintCode(String constraintCode) {
        this.constraintCode = constraintCode == null ? null : constraintCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_master.description
     *
     * @return the value of public.constraint_master.description
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_master.description
     *
     * @param description the value for public.constraint_master.description
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_master.default_kind
     *
     * @return the value of public.constraint_master.default_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getDefaultKind() {
        return defaultKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_master.default_kind
     *
     * @param defaultKind the value for public.constraint_master.default_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDefaultKind(String defaultKind) {
        this.defaultKind = defaultKind == null ? null : defaultKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_master.default_weight
     *
     * @return the value of public.constraint_master.default_weight
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getDefaultWeight() {
        return defaultWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_master.default_weight
     *
     * @param defaultWeight the value for public.constraint_master.default_weight
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDefaultWeight(Integer defaultWeight) {
        this.defaultWeight = defaultWeight;
    }
}