package io.github.riemr.shift.infrastructure.persistence.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RegisterDemandQuarterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public RegisterDemandQuarterExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andDemandIdIsNull() {
            addCriterion("demand_id is null");
            return (Criteria) this;
        }

        public Criteria andDemandIdIsNotNull() {
            addCriterion("demand_id is not null");
            return (Criteria) this;
        }

        public Criteria andDemandIdEqualTo(Long value) {
            addCriterion("demand_id =", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdNotEqualTo(Long value) {
            addCriterion("demand_id <>", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdGreaterThan(Long value) {
            addCriterion("demand_id >", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdGreaterThanOrEqualTo(Long value) {
            addCriterion("demand_id >=", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdLessThan(Long value) {
            addCriterion("demand_id <", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdLessThanOrEqualTo(Long value) {
            addCriterion("demand_id <=", value, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdIn(List<Long> values) {
            addCriterion("demand_id in", values, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdNotIn(List<Long> values) {
            addCriterion("demand_id not in", values, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdBetween(Long value1, Long value2) {
            addCriterion("demand_id between", value1, value2, "demandId");
            return (Criteria) this;
        }

        public Criteria andDemandIdNotBetween(Long value1, Long value2) {
            addCriterion("demand_id not between", value1, value2, "demandId");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIsNull() {
            addCriterion("store_code is null");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIsNotNull() {
            addCriterion("store_code is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCodeEqualTo(String value) {
            addCriterion("store_code =", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotEqualTo(String value) {
            addCriterion("store_code <>", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeGreaterThan(String value) {
            addCriterion("store_code >", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeGreaterThanOrEqualTo(String value) {
            addCriterion("store_code >=", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLessThan(String value) {
            addCriterion("store_code <", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLessThanOrEqualTo(String value) {
            addCriterion("store_code <=", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeLike(String value) {
            addCriterion("store_code like", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotLike(String value) {
            addCriterion("store_code not like", value, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeIn(List<String> values) {
            addCriterion("store_code in", values, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotIn(List<String> values) {
            addCriterion("store_code not in", values, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeBetween(String value1, String value2) {
            addCriterion("store_code between", value1, value2, "storeCode");
            return (Criteria) this;
        }

        public Criteria andStoreCodeNotBetween(String value1, String value2) {
            addCriterion("store_code not between", value1, value2, "storeCode");
            return (Criteria) this;
        }

        public Criteria andDemandDateIsNull() {
            addCriterion("demand_date is null");
            return (Criteria) this;
        }

        public Criteria andDemandDateIsNotNull() {
            addCriterion("demand_date is not null");
            return (Criteria) this;
        }

        public Criteria andDemandDateEqualTo(Date value) {
            addCriterionForJDBCDate("demand_date =", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("demand_date <>", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateGreaterThan(Date value) {
            addCriterionForJDBCDate("demand_date >", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("demand_date >=", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateLessThan(Date value) {
            addCriterionForJDBCDate("demand_date <", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("demand_date <=", value, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateIn(List<Date> values) {
            addCriterionForJDBCDate("demand_date in", values, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("demand_date not in", values, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("demand_date between", value1, value2, "demandDate");
            return (Criteria) this;
        }

        public Criteria andDemandDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("demand_date not between", value1, value2, "demandDate");
            return (Criteria) this;
        }

        public Criteria andSlotTimeIsNull() {
            addCriterion("slot_time is null");
            return (Criteria) this;
        }

        public Criteria andSlotTimeIsNotNull() {
            addCriterion("slot_time is not null");
            return (Criteria) this;
        }

        public Criteria andSlotTimeEqualTo(Date value) {
            addCriterionForJDBCTime("slot_time =", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("slot_time <>", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("slot_time >", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("slot_time >=", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeLessThan(Date value) {
            addCriterionForJDBCTime("slot_time <", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("slot_time <=", value, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeIn(List<Date> values) {
            addCriterionForJDBCTime("slot_time in", values, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("slot_time not in", values, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("slot_time between", value1, value2, "slotTime");
            return (Criteria) this;
        }

        public Criteria andSlotTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("slot_time not between", value1, value2, "slotTime");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsIsNull() {
            addCriterion("required_units is null");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsIsNotNull() {
            addCriterion("required_units is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsEqualTo(Integer value) {
            addCriterion("required_units =", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsNotEqualTo(Integer value) {
            addCriterion("required_units <>", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsGreaterThan(Integer value) {
            addCriterion("required_units >", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsGreaterThanOrEqualTo(Integer value) {
            addCriterion("required_units >=", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsLessThan(Integer value) {
            addCriterion("required_units <", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsLessThanOrEqualTo(Integer value) {
            addCriterion("required_units <=", value, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsIn(List<Integer> values) {
            addCriterion("required_units in", values, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsNotIn(List<Integer> values) {
            addCriterion("required_units not in", values, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsBetween(Integer value1, Integer value2) {
            addCriterion("required_units between", value1, value2, "requiredUnits");
            return (Criteria) this;
        }

        public Criteria andRequiredUnitsNotBetween(Integer value1, Integer value2) {
            addCriterion("required_units not between", value1, value2, "requiredUnits");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}