package io.github.riemr.shift.domain;

import java.util.ArrayList;
import java.util.List;

public class ConstraintMasterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public ConstraintMasterExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConstraintCodeIsNull() {
            addCriterion("constraint_code is null");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeIsNotNull() {
            addCriterion("constraint_code is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeEqualTo(String value) {
            addCriterion("constraint_code =", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotEqualTo(String value) {
            addCriterion("constraint_code <>", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeGreaterThan(String value) {
            addCriterion("constraint_code >", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeGreaterThanOrEqualTo(String value) {
            addCriterion("constraint_code >=", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLessThan(String value) {
            addCriterion("constraint_code <", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLessThanOrEqualTo(String value) {
            addCriterion("constraint_code <=", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLike(String value) {
            addCriterion("constraint_code like", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotLike(String value) {
            addCriterion("constraint_code not like", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeIn(List<String> values) {
            addCriterion("constraint_code in", values, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotIn(List<String> values) {
            addCriterion("constraint_code not in", values, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeBetween(String value1, String value2) {
            addCriterion("constraint_code between", value1, value2, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotBetween(String value1, String value2) {
            addCriterion("constraint_code not between", value1, value2, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDefaultKindIsNull() {
            addCriterion("default_kind is null");
            return (Criteria) this;
        }

        public Criteria andDefaultKindIsNotNull() {
            addCriterion("default_kind is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultKindEqualTo(String value) {
            addCriterion("default_kind =", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindNotEqualTo(String value) {
            addCriterion("default_kind <>", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindGreaterThan(String value) {
            addCriterion("default_kind >", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindGreaterThanOrEqualTo(String value) {
            addCriterion("default_kind >=", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindLessThan(String value) {
            addCriterion("default_kind <", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindLessThanOrEqualTo(String value) {
            addCriterion("default_kind <=", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindLike(String value) {
            addCriterion("default_kind like", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindNotLike(String value) {
            addCriterion("default_kind not like", value, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindIn(List<String> values) {
            addCriterion("default_kind in", values, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindNotIn(List<String> values) {
            addCriterion("default_kind not in", values, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindBetween(String value1, String value2) {
            addCriterion("default_kind between", value1, value2, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultKindNotBetween(String value1, String value2) {
            addCriterion("default_kind not between", value1, value2, "defaultKind");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightIsNull() {
            addCriterion("default_weight is null");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightIsNotNull() {
            addCriterion("default_weight is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightEqualTo(Integer value) {
            addCriterion("default_weight =", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightNotEqualTo(Integer value) {
            addCriterion("default_weight <>", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightGreaterThan(Integer value) {
            addCriterion("default_weight >", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_weight >=", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightLessThan(Integer value) {
            addCriterion("default_weight <", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightLessThanOrEqualTo(Integer value) {
            addCriterion("default_weight <=", value, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightIn(List<Integer> values) {
            addCriterion("default_weight in", values, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightNotIn(List<Integer> values) {
            addCriterion("default_weight not in", values, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightBetween(Integer value1, Integer value2) {
            addCriterion("default_weight between", value1, value2, "defaultWeight");
            return (Criteria) this;
        }

        public Criteria andDefaultWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("default_weight not between", value1, value2, "defaultWeight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_master
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}