package io.github.riemr.shift.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ConstraintSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public ConstraintSettingExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSettingIdIsNull() {
            addCriterion("setting_id is null");
            return (Criteria) this;
        }

        public Criteria andSettingIdIsNotNull() {
            addCriterion("setting_id is not null");
            return (Criteria) this;
        }

        public Criteria andSettingIdEqualTo(Long value) {
            addCriterion("setting_id =", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdNotEqualTo(Long value) {
            addCriterion("setting_id <>", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdGreaterThan(Long value) {
            addCriterion("setting_id >", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdGreaterThanOrEqualTo(Long value) {
            addCriterion("setting_id >=", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdLessThan(Long value) {
            addCriterion("setting_id <", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdLessThanOrEqualTo(Long value) {
            addCriterion("setting_id <=", value, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdIn(List<Long> values) {
            addCriterion("setting_id in", values, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdNotIn(List<Long> values) {
            addCriterion("setting_id not in", values, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdBetween(Long value1, Long value2) {
            addCriterion("setting_id between", value1, value2, "settingId");
            return (Criteria) this;
        }

        public Criteria andSettingIdNotBetween(Long value1, Long value2) {
            addCriterion("setting_id not between", value1, value2, "settingId");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeIsNull() {
            addCriterion("constraint_code is null");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeIsNotNull() {
            addCriterion("constraint_code is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeEqualTo(String value) {
            addCriterion("constraint_code =", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotEqualTo(String value) {
            addCriterion("constraint_code <>", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeGreaterThan(String value) {
            addCriterion("constraint_code >", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeGreaterThanOrEqualTo(String value) {
            addCriterion("constraint_code >=", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLessThan(String value) {
            addCriterion("constraint_code <", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLessThanOrEqualTo(String value) {
            addCriterion("constraint_code <=", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeLike(String value) {
            addCriterion("constraint_code like", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotLike(String value) {
            addCriterion("constraint_code not like", value, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeIn(List<String> values) {
            addCriterion("constraint_code in", values, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotIn(List<String> values) {
            addCriterion("constraint_code not in", values, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeBetween(String value1, String value2) {
            addCriterion("constraint_code between", value1, value2, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andConstraintCodeNotBetween(String value1, String value2) {
            addCriterion("constraint_code not between", value1, value2, "constraintCode");
            return (Criteria) this;
        }

        public Criteria andScopeTypeIsNull() {
            addCriterion("scope_type is null");
            return (Criteria) this;
        }

        public Criteria andScopeTypeIsNotNull() {
            addCriterion("scope_type is not null");
            return (Criteria) this;
        }

        public Criteria andScopeTypeEqualTo(String value) {
            addCriterion("scope_type =", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeNotEqualTo(String value) {
            addCriterion("scope_type <>", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeGreaterThan(String value) {
            addCriterion("scope_type >", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("scope_type >=", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeLessThan(String value) {
            addCriterion("scope_type <", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeLessThanOrEqualTo(String value) {
            addCriterion("scope_type <=", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeLike(String value) {
            addCriterion("scope_type like", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeNotLike(String value) {
            addCriterion("scope_type not like", value, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeIn(List<String> values) {
            addCriterion("scope_type in", values, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeNotIn(List<String> values) {
            addCriterion("scope_type not in", values, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeBetween(String value1, String value2) {
            addCriterion("scope_type between", value1, value2, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeTypeNotBetween(String value1, String value2) {
            addCriterion("scope_type not between", value1, value2, "scopeType");
            return (Criteria) this;
        }

        public Criteria andScopeIdIsNull() {
            addCriterion("scope_id is null");
            return (Criteria) this;
        }

        public Criteria andScopeIdIsNotNull() {
            addCriterion("scope_id is not null");
            return (Criteria) this;
        }

        public Criteria andScopeIdEqualTo(String value) {
            addCriterion("scope_id =", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdNotEqualTo(String value) {
            addCriterion("scope_id <>", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdGreaterThan(String value) {
            addCriterion("scope_id >", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdGreaterThanOrEqualTo(String value) {
            addCriterion("scope_id >=", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdLessThan(String value) {
            addCriterion("scope_id <", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdLessThanOrEqualTo(String value) {
            addCriterion("scope_id <=", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdLike(String value) {
            addCriterion("scope_id like", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdNotLike(String value) {
            addCriterion("scope_id not like", value, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdIn(List<String> values) {
            addCriterion("scope_id in", values, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdNotIn(List<String> values) {
            addCriterion("scope_id not in", values, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdBetween(String value1, String value2) {
            addCriterion("scope_id between", value1, value2, "scopeId");
            return (Criteria) this;
        }

        public Criteria andScopeIdNotBetween(String value1, String value2) {
            addCriterion("scope_id not between", value1, value2, "scopeId");
            return (Criteria) this;
        }

        public Criteria andNumericValueIsNull() {
            addCriterion("numeric_value is null");
            return (Criteria) this;
        }

        public Criteria andNumericValueIsNotNull() {
            addCriterion("numeric_value is not null");
            return (Criteria) this;
        }

        public Criteria andNumericValueEqualTo(BigDecimal value) {
            addCriterion("numeric_value =", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueNotEqualTo(BigDecimal value) {
            addCriterion("numeric_value <>", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueGreaterThan(BigDecimal value) {
            addCriterion("numeric_value >", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("numeric_value >=", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueLessThan(BigDecimal value) {
            addCriterion("numeric_value <", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("numeric_value <=", value, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueIn(List<BigDecimal> values) {
            addCriterion("numeric_value in", values, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueNotIn(List<BigDecimal> values) {
            addCriterion("numeric_value not in", values, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("numeric_value between", value1, value2, "numericValue");
            return (Criteria) this;
        }

        public Criteria andNumericValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("numeric_value not between", value1, value2, "numericValue");
            return (Criteria) this;
        }

        public Criteria andTextValueIsNull() {
            addCriterion("text_value is null");
            return (Criteria) this;
        }

        public Criteria andTextValueIsNotNull() {
            addCriterion("text_value is not null");
            return (Criteria) this;
        }

        public Criteria andTextValueEqualTo(String value) {
            addCriterion("text_value =", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueNotEqualTo(String value) {
            addCriterion("text_value <>", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueGreaterThan(String value) {
            addCriterion("text_value >", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueGreaterThanOrEqualTo(String value) {
            addCriterion("text_value >=", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueLessThan(String value) {
            addCriterion("text_value <", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueLessThanOrEqualTo(String value) {
            addCriterion("text_value <=", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueLike(String value) {
            addCriterion("text_value like", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueNotLike(String value) {
            addCriterion("text_value not like", value, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueIn(List<String> values) {
            addCriterion("text_value in", values, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueNotIn(List<String> values) {
            addCriterion("text_value not in", values, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueBetween(String value1, String value2) {
            addCriterion("text_value between", value1, value2, "textValue");
            return (Criteria) this;
        }

        public Criteria andTextValueNotBetween(String value1, String value2) {
            addCriterion("text_value not between", value1, value2, "textValue");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideIsNull() {
            addCriterion("weight_override is null");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideIsNotNull() {
            addCriterion("weight_override is not null");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideEqualTo(Integer value) {
            addCriterion("weight_override =", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideNotEqualTo(Integer value) {
            addCriterion("weight_override <>", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideGreaterThan(Integer value) {
            addCriterion("weight_override >", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight_override >=", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideLessThan(Integer value) {
            addCriterion("weight_override <", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideLessThanOrEqualTo(Integer value) {
            addCriterion("weight_override <=", value, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideIn(List<Integer> values) {
            addCriterion("weight_override in", values, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideNotIn(List<Integer> values) {
            addCriterion("weight_override not in", values, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideBetween(Integer value1, Integer value2) {
            addCriterion("weight_override between", value1, value2, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andWeightOverrideNotBetween(Integer value1, Integer value2) {
            addCriterion("weight_override not between", value1, value2, "weightOverride");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromIsNull() {
            addCriterion("effective_from is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromIsNotNull() {
            addCriterion("effective_from is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromEqualTo(Date value) {
            addCriterionForJDBCDate("effective_from =", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromNotEqualTo(Date value) {
            addCriterionForJDBCDate("effective_from <>", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromGreaterThan(Date value) {
            addCriterionForJDBCDate("effective_from >", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_from >=", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromLessThan(Date value) {
            addCriterionForJDBCDate("effective_from <", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_from <=", value, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromIn(List<Date> values) {
            addCriterionForJDBCDate("effective_from in", values, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromNotIn(List<Date> values) {
            addCriterionForJDBCDate("effective_from not in", values, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_from between", value1, value2, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveFromNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_from not between", value1, value2, "effectiveFrom");
            return (Criteria) this;
        }

        public Criteria andEffectiveToIsNull() {
            addCriterion("effective_to is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveToIsNotNull() {
            addCriterion("effective_to is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveToEqualTo(Date value) {
            addCriterionForJDBCDate("effective_to =", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToNotEqualTo(Date value) {
            addCriterionForJDBCDate("effective_to <>", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToGreaterThan(Date value) {
            addCriterionForJDBCDate("effective_to >", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_to >=", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToLessThan(Date value) {
            addCriterionForJDBCDate("effective_to <", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_to <=", value, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToIn(List<Date> values) {
            addCriterionForJDBCDate("effective_to in", values, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToNotIn(List<Date> values) {
            addCriterionForJDBCDate("effective_to not in", values, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_to between", value1, value2, "effectiveTo");
            return (Criteria) this;
        }

        public Criteria andEffectiveToNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_to not between", value1, value2, "effectiveTo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_setting
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}