package io.github.riemr.shift.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ConstraintSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.setting_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Long settingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String constraintCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.scope_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String scopeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.scope_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String scopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.numeric_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private BigDecimal numericValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.text_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String textValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.weight_override
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer weightOverride;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.effective_from
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date effectiveFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.constraint_setting.effective_to
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date effectiveTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.setting_id
     *
     * @return the value of public.constraint_setting.setting_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Long getSettingId() {
        return settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.setting_id
     *
     * @param settingId the value for public.constraint_setting.setting_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setSettingId(Long settingId) {
        this.settingId = settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.constraint_code
     *
     * @return the value of public.constraint_setting.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getConstraintCode() {
        return constraintCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.constraint_code
     *
     * @param constraintCode the value for public.constraint_setting.constraint_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setConstraintCode(String constraintCode) {
        this.constraintCode = constraintCode == null ? null : constraintCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.scope_type
     *
     * @return the value of public.constraint_setting.scope_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getScopeType() {
        return scopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.scope_type
     *
     * @param scopeType the value for public.constraint_setting.scope_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setScopeType(String scopeType) {
        this.scopeType = scopeType == null ? null : scopeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.scope_id
     *
     * @return the value of public.constraint_setting.scope_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getScopeId() {
        return scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.scope_id
     *
     * @param scopeId the value for public.constraint_setting.scope_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setScopeId(String scopeId) {
        this.scopeId = scopeId == null ? null : scopeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.numeric_value
     *
     * @return the value of public.constraint_setting.numeric_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public BigDecimal getNumericValue() {
        return numericValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.numeric_value
     *
     * @param numericValue the value for public.constraint_setting.numeric_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setNumericValue(BigDecimal numericValue) {
        this.numericValue = numericValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.text_value
     *
     * @return the value of public.constraint_setting.text_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getTextValue() {
        return textValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.text_value
     *
     * @param textValue the value for public.constraint_setting.text_value
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setTextValue(String textValue) {
        this.textValue = textValue == null ? null : textValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.weight_override
     *
     * @return the value of public.constraint_setting.weight_override
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getWeightOverride() {
        return weightOverride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.weight_override
     *
     * @param weightOverride the value for public.constraint_setting.weight_override
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setWeightOverride(Integer weightOverride) {
        this.weightOverride = weightOverride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.effective_from
     *
     * @return the value of public.constraint_setting.effective_from
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getEffectiveFrom() {
        return effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.effective_from
     *
     * @param effectiveFrom the value for public.constraint_setting.effective_from
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEffectiveFrom(Date effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.constraint_setting.effective_to
     *
     * @return the value of public.constraint_setting.effective_to
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getEffectiveTo() {
        return effectiveTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.constraint_setting.effective_to
     *
     * @param effectiveTo the value for public.constraint_setting.effective_to
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }
}