package io.github.riemr.shift.domain;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
public class Employee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.employee_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.short_follow
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Short shortFollow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.max_work_minutes_day
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer maxWorkMinutesDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.max_work_days_month
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer maxWorkDaysMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.employee
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.employee_code
     *
     * @return the value of public.employee.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.employee_code
     *
     * @param employeeCode the value for public.employee.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.store_code
     *
     * @return the value of public.employee.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.store_code
     *
     * @param storeCode the value for public.employee.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.employee_name
     *
     * @return the value of public.employee.employee_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.employee_name
     *
     * @param employeeName the value for public.employee.employee_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.short_follow
     *
     * @return the value of public.employee.short_follow
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Short getShortFollow() {
        return shortFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.short_follow
     *
     * @param shortFollow the value for public.employee.short_follow
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setShortFollow(Short shortFollow) {
        this.shortFollow = shortFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.max_work_minutes_day
     *
     * @return the value of public.employee.max_work_minutes_day
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getMaxWorkMinutesDay() {
        return maxWorkMinutesDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.max_work_minutes_day
     *
     * @param maxWorkMinutesDay the value for public.employee.max_work_minutes_day
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setMaxWorkMinutesDay(Integer maxWorkMinutesDay) {
        this.maxWorkMinutesDay = maxWorkMinutesDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.max_work_days_month
     *
     * @return the value of public.employee.max_work_days_month
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getMaxWorkDaysMonth() {
        return maxWorkDaysMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.max_work_days_month
     *
     * @param maxWorkDaysMonth the value for public.employee.max_work_days_month
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setMaxWorkDaysMonth(Integer maxWorkDaysMonth) {
        this.maxWorkDaysMonth = maxWorkDaysMonth;
    }
}