package io.github.riemr.shift.domain;

import java.io.Serializable;
import java.util.Date;

public class EmployeeRequest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.request_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.request_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date requestDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.from_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date fromTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.to_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date toTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.request_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String requestKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_request.note
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.request_id
     *
     * @return the value of public.employee_request.request_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.request_id
     *
     * @param requestId the value for public.employee_request.request_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.store_code
     *
     * @return the value of public.employee_request.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.store_code
     *
     * @param storeCode the value for public.employee_request.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.employee_code
     *
     * @return the value of public.employee_request.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.employee_code
     *
     * @param employeeCode the value for public.employee_request.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.request_date
     *
     * @return the value of public.employee_request.request_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getRequestDate() {
        return requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.request_date
     *
     * @param requestDate the value for public.employee_request.request_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.from_time
     *
     * @return the value of public.employee_request.from_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getFromTime() {
        return fromTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.from_time
     *
     * @param fromTime the value for public.employee_request.from_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.to_time
     *
     * @return the value of public.employee_request.to_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getToTime() {
        return toTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.to_time
     *
     * @param toTime the value for public.employee_request.to_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setToTime(Date toTime) {
        this.toTime = toTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.request_kind
     *
     * @return the value of public.employee_request.request_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getRequestKind() {
        return requestKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.request_kind
     *
     * @param requestKind the value for public.employee_request.request_kind
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRequestKind(String requestKind) {
        this.requestKind = requestKind == null ? null : requestKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.priority
     *
     * @return the value of public.employee_request.priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.priority
     *
     * @param priority the value for public.employee_request.priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_request.note
     *
     * @return the value of public.employee_request.note
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_request.note
     *
     * @param note the value for public.employee_request.note
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}