package io.github.riemr.shift.domain;

import java.io.Serializable;

public class EmployeeRegisterSkill extends EmployeeRegisterSkillKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_register_skill.skill_level
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Short skillLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_register_skill.skill_level
     *
     * @return the value of public.employee_register_skill.skill_level
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Short getSkillLevel() {
        return skillLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_register_skill.skill_level
     *
     * @param skillLevel the value for public.employee_register_skill.skill_level
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setSkillLevel(Short skillLevel) {
        this.skillLevel = skillLevel;
    }
}