package io.github.riemr.shift.domain;

import java.io.Serializable;

public class EmployeeRegisterSkillKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_register_skill.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_register_skill.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee_register_skill.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer registerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_register_skill.store_code
     *
     * @return the value of public.employee_register_skill.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_register_skill.store_code
     *
     * @param storeCode the value for public.employee_register_skill.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_register_skill.employee_code
     *
     * @return the value of public.employee_register_skill.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_register_skill.employee_code
     *
     * @param employeeCode the value for public.employee_register_skill.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee_register_skill.register_no
     *
     * @return the value of public.employee_register_skill.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee_register_skill.register_no
     *
     * @param registerNo the value for public.employee_register_skill.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRegisterNo(Integer registerNo) {
        this.registerNo = registerNo;
    }
}