package io.github.riemr.shift.domain;

import java.io.Serializable;
import java.util.Date;

public class RegisterDemandQuarter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_demand_quarter.demand_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Long demandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_demand_quarter.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_demand_quarter.demand_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date demandDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_demand_quarter.slot_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date slotTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_demand_quarter.required_units
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer requiredUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_demand_quarter.demand_id
     *
     * @return the value of public.register_demand_quarter.demand_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_demand_quarter.demand_id
     *
     * @param demandId the value for public.register_demand_quarter.demand_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_demand_quarter.store_code
     *
     * @return the value of public.register_demand_quarter.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_demand_quarter.store_code
     *
     * @param storeCode the value for public.register_demand_quarter.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_demand_quarter.demand_date
     *
     * @return the value of public.register_demand_quarter.demand_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getDemandDate() {
        return demandDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_demand_quarter.demand_date
     *
     * @param demandDate the value for public.register_demand_quarter.demand_date
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setDemandDate(Date demandDate) {
        this.demandDate = demandDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_demand_quarter.slot_time
     *
     * @return the value of public.register_demand_quarter.slot_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getSlotTime() {
        return slotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_demand_quarter.slot_time
     *
     * @param slotTime the value for public.register_demand_quarter.slot_time
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setSlotTime(Date slotTime) {
        this.slotTime = slotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_demand_quarter.required_units
     *
     * @return the value of public.register_demand_quarter.required_units
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getRequiredUnits() {
        return requiredUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_demand_quarter.required_units
     *
     * @param requiredUnits the value for public.register_demand_quarter.required_units
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRequiredUnits(Integer requiredUnits) {
        this.requiredUnits = requiredUnits;
    }
}