package io.github.riemr.shift.domain;

import java.io.Serializable;

public class RegisterType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_type.type_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register_type.type_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_type.type_code
     *
     * @return the value of public.register_type.type_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_type.type_code
     *
     * @param typeCode the value for public.register_type.type_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register_type.type_name
     *
     * @return the value of public.register_type.type_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register_type.type_name
     *
     * @param typeName the value for public.register_type.type_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}