package io.github.riemr.shift.domain;

import java.io.Serializable;

public class Register extends RegisterKey implements Serializable {
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register.register_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String registerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register.short_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register.open_priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer openPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String registerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.register.is_auto_open_target
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Boolean isAutoOpenTarget;

    private Integer maxAllowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register.register_name
     *
     * @return the value of public.register.register_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getRegisterName() {
        return registerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register.register_name
     *
     * @param registerName the value for public.register.register_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRegisterName(String registerName) {
        this.registerName = registerName == null ? null : registerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register.short_name
     *
     * @return the value of public.register.short_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register.short_name
     *
     * @param shortName the value for public.register.short_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register.open_priority
     *
     * @return the value of public.register.open_priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getOpenPriority() {
        return openPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register.open_priority
     *
     * @param openPriority the value for public.register.open_priority
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setOpenPriority(Integer openPriority) {
        this.openPriority = openPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register.register_type
     *
     * @return the value of public.register.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register.register_type
     *
     * @param registerType the value for public.register.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRegisterType(String registerType) {
        this.registerType = registerType == null ? null : registerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.register.is_auto_open_target
     *
     * @return the value of public.register.is_auto_open_target
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Boolean getIsAutoOpenTarget() {
        return isAutoOpenTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.register.is_auto_open_target
     *
     * @param isAutoOpenTarget the value for public.register.is_auto_open_target
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setIsAutoOpenTarget(Boolean isAutoOpenTarget) {
        this.isAutoOpenTarget = isAutoOpenTarget;
    }

    public Integer getMaxAllowance(){
        return maxAllowance;
    }

    public void setMaxAllowance(Integer maxAllowance){
        this.maxAllowance = maxAllowance;
    }
}