package io.github.riemr.shift.domain;

import java.io.Serializable;
import java.util.Date;

public class ShiftAssignment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.shift_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Long shiftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Integer registerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.start_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date startAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.end_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shift_assignment.created_by
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.shift_id
     *
     * @return the value of public.shift_assignment.shift_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Long getShiftId() {
        return shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.shift_id
     *
     * @param shiftId the value for public.shift_assignment.shift_id
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setShiftId(Long shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.store_code
     *
     * @return the value of public.shift_assignment.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.store_code
     *
     * @param storeCode the value for public.shift_assignment.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.employee_code
     *
     * @return the value of public.shift_assignment.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.employee_code
     *
     * @param employeeCode the value for public.shift_assignment.employee_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.register_no
     *
     * @return the value of public.shift_assignment.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Integer getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.register_no
     *
     * @param registerNo the value for public.shift_assignment.register_no
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setRegisterNo(Integer registerNo) {
        this.registerNo = registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.start_at
     *
     * @return the value of public.shift_assignment.start_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.start_at
     *
     * @param startAt the value for public.shift_assignment.start_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.end_at
     *
     * @return the value of public.shift_assignment.end_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.end_at
     *
     * @param endAt the value for public.shift_assignment.end_at
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shift_assignment.created_by
     *
     * @return the value of public.shift_assignment.created_by
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shift_assignment.created_by
     *
     * @param createdBy the value for public.shift_assignment.created_by
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }
}