package io.github.riemr.shift.domain;

import java.io.Serializable;

public class Store implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.store_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.timezone
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private String timezone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.store_code
     *
     * @return the value of public.store.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.store_code
     *
     * @param storeCode the value for public.store.store_code
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.store_name
     *
     * @return the value of public.store.store_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.store_name
     *
     * @param storeName the value for public.store.store_name
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.timezone
     *
     * @return the value of public.store.timezone
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.timezone
     *
     * @param timezone the value for public.store.timezone
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }
}