package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.ConstraintMaster;
import io.github.riemr.shift.domain.ConstraintMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstraintMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(ConstraintMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(ConstraintMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(String constraintCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(ConstraintMaster row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(ConstraintMaster row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<ConstraintMaster> selectByExample(ConstraintMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    ConstraintMaster selectByPrimaryKey(String constraintCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") ConstraintMaster row, @Param("example") ConstraintMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") ConstraintMaster row, @Param("example") ConstraintMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(ConstraintMaster row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_master
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(ConstraintMaster row);

    List<ConstraintMaster> selectAll();
}