package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.ConstraintSetting;
import io.github.riemr.shift.domain.ConstraintSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstraintSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(ConstraintSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(ConstraintSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(ConstraintSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(ConstraintSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<ConstraintSetting> selectByExample(ConstraintSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    ConstraintSetting selectByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") ConstraintSetting row, @Param("example") ConstraintSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") ConstraintSetting row, @Param("example") ConstraintSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(ConstraintSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.constraint_setting
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(ConstraintSetting row);
}