package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.EmployeeRegisterSkill;
import io.github.riemr.shift.domain.EmployeeRegisterSkillExample;
import io.github.riemr.shift.domain.EmployeeRegisterSkillKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeRegisterSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(EmployeeRegisterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(EmployeeRegisterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(EmployeeRegisterSkillKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(EmployeeRegisterSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(EmployeeRegisterSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<EmployeeRegisterSkill> selectByExample(EmployeeRegisterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    EmployeeRegisterSkill selectByPrimaryKey(EmployeeRegisterSkillKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") EmployeeRegisterSkill row, @Param("example") EmployeeRegisterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") EmployeeRegisterSkill row, @Param("example") EmployeeRegisterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(EmployeeRegisterSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_register_skill
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(EmployeeRegisterSkill row);
}