package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.infrastructure.persistence.entity.EmployeeRequest;
import io.github.riemr.shift.infrastructure.persistence.entity.EmployeeRequestExample;

import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(EmployeeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(EmployeeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(Long requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(EmployeeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(EmployeeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<EmployeeRequest> selectByExample(EmployeeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    EmployeeRequest selectByPrimaryKey(Long requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") EmployeeRequest row, @Param("example") EmployeeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") EmployeeRequest row, @Param("example") EmployeeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(EmployeeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee_request
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(EmployeeRequest row);

    List<EmployeeRequest> selectByMonth(@Param("targetDate") LocalDate targetDate);
    
    // カスタムメソッド
    List<EmployeeRequest> selectByDateRange(@Param("fromDate") LocalDate fromDate, @Param("toDate") LocalDate toDate);
    
    EmployeeRequest selectByEmployeeAndDate(@Param("employeeCode") String employeeCode, @Param("requestDate") LocalDate requestDate);
    
    List<EmployeeRequest> selectByEmployeeAndDateRange(@Param("employeeCode") String employeeCode, @Param("fromDate") LocalDate fromDate, @Param("toDate") LocalDate toDate);
    
    int deleteById(@Param("id") Long id);

    int deleteByEmployeeAndDate(@Param("storeCode") String storeCode,
                                @Param("employeeCode") String employeeCode,
                                @Param("requestDate") LocalDate requestDate);
}
