package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.RegisterType;
import io.github.riemr.shift.domain.RegisterTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(RegisterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(RegisterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(String typeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(RegisterType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(RegisterType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<RegisterType> selectByExample(RegisterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    RegisterType selectByPrimaryKey(String typeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") RegisterType row, @Param("example") RegisterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") RegisterType row, @Param("example") RegisterTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(RegisterType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_type
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(RegisterType row);
}