package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.Register;
import io.github.riemr.shift.domain.RegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(Register row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(Register row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<Register> selectByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") Register row, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") Register row, @Param("example") RegisterExample example);
}