package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.infrastructure.persistence.entity.RegisterDemandQuarter;
import io.github.riemr.shift.infrastructure.persistence.entity.RegisterDemandQuarterExample;

import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterDemandQuarterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(RegisterDemandQuarterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(RegisterDemandQuarterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(Long demandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(RegisterDemandQuarter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(RegisterDemandQuarter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<RegisterDemandQuarter> selectByExample(RegisterDemandQuarterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    RegisterDemandQuarter selectByPrimaryKey(Long demandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") RegisterDemandQuarter row, @Param("example") RegisterDemandQuarterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") RegisterDemandQuarter row, @Param("example") RegisterDemandQuarterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(RegisterDemandQuarter row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.register_demand_quarter
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(RegisterDemandQuarter row);

    List<RegisterDemandQuarter> selectByStoreAndDate(@Param("storeCode") String storeCde, @Param("targetDate") LocalDate targetDate);

    void deleteByStoreAndDate(@Param("storeCode") String storeCode, @Param("targetDate") LocalDate targetDate);

    void batchInsert(@Param("list") List<RegisterDemandQuarter> quarters);

    List<RegisterDemandQuarter> selectByMonth(@Param("targetMonth") LocalDate targetMonth);

    // custom upsert on natural key (store_code, demand_date, slot_time)
    int upsert(RegisterDemandQuarter row);
}
