package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.ShiftAssignment;
import io.github.riemr.shift.domain.ShiftAssignmentExample;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ShiftAssignmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(ShiftAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(ShiftAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(Long shiftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(ShiftAssignment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(ShiftAssignment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<ShiftAssignment> selectByExample(ShiftAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    ShiftAssignment selectByPrimaryKey(Long shiftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") ShiftAssignment row, @Param("example") ShiftAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") ShiftAssignment row, @Param("example") ShiftAssignmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(ShiftAssignment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shift_assignment
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(ShiftAssignment row);

    /** 指定月に含まれるシフトをすべて取得 */
    List<ShiftAssignment> selectByMonth(@Param("from") LocalDate from,
            @Param("to") LocalDate to);

    /**
     * Solver 結果をまとめて書き戻す
     * key: shiftId, value: employeeCode
     */
    int bulkUpdateEmployee(@Param("map") Map<Long, String> map);
}