package io.github.riemr.shift.infrastructure.mapper;

import io.github.riemr.shift.domain.Store;
import io.github.riemr.shift.domain.StoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    long countByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int deleteByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insert(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int insertSelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    List<Store> selectByExample(StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    Store selectByPrimaryKey(String storeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByExample(@Param("row") Store row, @Param("example") StoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKeySelective(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated Fri Jul 11 07:14:31 JST 2025
     */
    int updateByPrimaryKey(Store row);
}